// flow-typed signature: 8e8d869d4c783683af52d649721998ea
// flow-typed version: <<STUB>>/auth0-lock_v11.9.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-lock' {
  declare module.exports: any;
}
