// flow-typed signature: e40a45ecc74ad89c30173a3842a87b95
// flow-typed version: <<STUB>>/redux-reqseq_v0.6.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-reqseq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-reqseq' {
  declare module.exports: any;
}
